-- The single consumer-visible identity of the derived assets crossing the
-- romdump boundary: cache formats, generated schemas, and binary format
-- versions. Producers and runtime read these constants through the libs/assets
-- cache modules rather than carrying their own literals, so a format change is
-- one edit. `revision` is the manual escape hatch for a shared contract
-- behavior change that alters generated bytes without changing any schema
-- constant; compiler implementation versions are deliberately absent (producer
-- freshness belongs to the romdump source fingerprint).
--
-- revision 2: the compiled NSBTP payload drops the redundant
-- keyCount/numTextures/numPalettes counts (sampler and gate trust the
-- arrays).
--
-- map sceneSchema 7: map/neighbor terrain batches can now serialize
-- alphaClass = "mixed" (AlphaClassifier v2: a MODULATE polygon at alpha 31
-- with both opaque and partial texture alpha texels splits into an opaque
-- and a translucent subpass instead of being forced wholly translucent).
--
-- fieldActors schema 2: the visual definition's render.alphaClass now comes
-- from AlphaClassifier v2 (polygon-mode-aware, final-alpha-driven
-- classification); the vocabulary a stale v1 cache could have baked in is
-- no longer trustworthy.
--
-- fieldActors index 3: the runtime avatar capability is a semantic state map.
-- Each playable gender carries exactly the fourteen visual states with
-- compiled sprite IDs, so runtime state transitions resolve any visual
-- without source interpretation or fallback. A stale index without the state
-- maps must fail readiness; only the index identity changes.
--
-- fieldActors schema 3/cache v2: generated visuals carry the required
-- source-independent idle presentation profile and the required semantic
-- gesture clip map. Each idle pose segment carries a finite
-- displayOffsetY required for phase-correct presentation, and each visual
-- carries a required gestures table. Non-empty semantic gesture clips belong
-- to atlas/billboard visuals with validated poses and finite display offsets
-- for the supported sprite-specific clips (nurse_bow, give, receive); static
-- models require the empty gesture table because the current static
-- presentation has no gesture frame selection. A stale visual cannot supply
-- the actor's idle cadence, display offsets, or gesture presentation safely.
--
-- fieldUi schema 6: wayfinding rects become final 48x32 surfaces. Each
-- (type, map) rect is a 6x4 arrangement (48px wide, 32px tall) composed at
-- build time from the original 24 8x8 tiles, instead of a raw 192x8 strip.
--
-- fieldUi schema 13: the Start Menu section carries the source-independent
-- label palette roles (foreground/shadow from the label window palette bank,
-- background as the same source RGB with zero alpha so glyph
-- background-class pixels reveal already-rendered chrome instead of
-- repainting it). A stale cache without that record must fail readiness.
--
-- fieldUi schema 12: the normal naming section carries full generated
-- subject/cursor animations with corrected source geometry (the page
-- overlay rests at x=11, home controls carry their post-parent-transform
-- anchors, keyboard text starts at screen x=27) plus the per-frame
-- cursor pulse-mask role selecting source palette entry 29, so a stale
-- pre-change cache with static naming visuals must fail readiness.
--
-- fieldUi schema 11: the Start Menu section publishes the SUB-side
-- interactive selector (the seven normal position records with anchors,
-- label windows, touch bounds, and ordered directional candidates, plus the
-- cancel bound) and source-composed icon visuals (normal/selected atlas
-- records with signed frame offsets, the Bag female pair as a first-class
-- variant) instead of the ten-slot grid, the fixed crop rects, and the
-- slot-keyed bases/windows. A stale pre-change cache without that section
-- must fail readiness.
--
-- fieldUi schema 10: the normal naming section carries the source-window
--- text geometry and the OAM-composed control/cursor/slot/subject visuals
--- (semantic sprite records with canonical anchors plus generated frame
--- offsets) instead of chrome alone, so a stale pre-change cache without
--- that section must fail readiness.
--
-- fieldUi schema 9: the Start Menu section carries the retail icon-sprite
-- contract (the 13-row icon table with label-bank ids, the 7 context rows,
-- the shared icon/highlight atlases and palette record, the action-to-icon
-- map, sprite bases, label windows, and main/sub chrome) instead of the
-- per-action background-surface rects, and the main panel compiles with
-- source-zero transparency. A stale pre-change cache without that section
-- must fail readiness.
--
-- fieldUi schema 8: the manifest carries the required source-independent
-- normal naming chrome (one opaque 256x192 base plus the exact Upper, Lower,
-- and Symbols 256x112 page overlays at the canonical y=80 placement), so a
-- stale pre-change cache without that section must fail readiness.
--
-- fieldUi schema 5: signposts.types entries gain per-type palette banks
-- (one 16-color table per source type) and per-type frameTiles rectangles.
-- The old global signposts.frame.tiles authority is removed. Each type's
-- frame strip uses its own palette for precolored rendering. signposts
-- gains textColors (the foreground/shadow/background palette slots), so
-- text rendering no longer has to hardcode the source's fixed 2/10/15 slots.
--
-- fieldUi schema 14: dialogueFrames publishes each selected frame's palette
-- because focus-indicator masks are tinted by their owning window.
--
-- fieldUi schema 15: the manifest carries the required two-row choice
-- prompt section (the compact 48x32 button geometry with normal/selected
-- visuals per row, every visual resolved through the shared asset index by
-- semantic id), so a stale pre-change cache without that section must fail
-- readiness.
-- fieldUi schema 17: selected name slots preserve their NANR animation and
-- Pokémon naming carries the source anchor and mon-icon frame selection.
-- Species pixels remain owned by the shared mon-icon atlas.
-- fieldUi schema 18: Pokémon naming preserves every validated source OAM
-- placement and carries generated gender marker animations.
--
-- fieldUi schema 19: Pokémon naming publishes visible semantic dynamic-icon
-- parts and consumer-safe animation geometry; icon pixels remain in the
-- shared mon-icon atlas.
-- fieldUi schema 20: Naming Screen interaction geometry uses fixed canonical
-- source positions; visual records remain replaceable at those positions.
--
-- fieldUi schema 16: dialogueFrames also publishes the fixed standard
-- Yes/No frame strip and palette independently of selectable user frames.
--
-- fieldUi schema 3: signpost wayfinding becomes a per-(type,map) rect table
-- (signposts.types[N].wayfinding[map]) and the manifest drops the
-- startMenu.icons mapping (no runtime consumer remains; the icon art is
-- baked into the background surface).
--
-- fieldUi schema 2: the generated field-UI manifest drops the sounds
-- section (the branch no longer compiles Start Menu effects).
--
-- messages cacheFormat v2: YESNO tokens classify as focus_indicator in the
-- persisted bank streams (runtime playback rejects the old
-- unsupported_control classification), so a stale bank must not be misread.
--
-- font cacheFormat/schema v2: the compiled definition gains seven color bands
-- and a focus-indicator PNG, and the marker hashes font member 6, so a stale
-- pre-change font cache must not pass readiness.
-- intro OBJ geometry: animated widgets retain one OAM-origin pivot across
-- frames and publish source-reference centers for responsive placement.
-- field map schema 9: generated object events publish semantic movement types
-- map scene schema 10: Elm's Lab publishes the generated starter-ball model
-- reference and its normalized runtime placement transforms.
-- instead of raw HGSS movement selectors.
--
-- revision 11: prepared stages carry their generation, epoch, and canonical
-- job identity, and each successful publication leaves a generation receipt
-- beside the family output, so a receipt plus the family validator proves
-- the current generation without recompiling.
--
-- revision 12: the audio runtime index is independently attestable before
-- full audio completion. The audio catalog owns the index and its catalog
-- completion; the family summary owns only exhaustive provenance and
-- completion.
--
-- world schema 1: the world manifest is a structural catalog derived from
-- source analysis alone. Membership means the source map is structurally
-- loadable, never that its scene geometry compiled; every record carries the
-- resolver-normalized world origin alongside its source identities.

local DerivedAssetContract = {}

DerivedAssetContract.revision = 12

DerivedAssetContract.map = {
  cacheFormat = "map-cache-v7",
  -- v9: neighboring matrix cells carry required normalized X/Y/Z placement;
  -- runtime consumers preserve the source-relative vertical placement.
  -- v6: render-state extension over v5 — scenes carry the real HGSS field
  -- edge-color table (scene.edgeColors), every batch/material record carries
  -- the per-polygon fog gate (fogEnabled, PolygonState.FIELDS), and scenes
  -- carry the map's base weather ID plus its resolved global HGSS fog preset
  -- (scene.weatherId, scene.fog).
  sceneSchema = "g4-map-scene-v10",
  terrainSchema = "g4-terrain-surfaces-v1",
  collisionVersion = 1,
}

DerivedAssetContract.world = {
  schema = "g4-world-v1",
}

DerivedAssetContract.fieldCells = {
  -- v3 adds independently published cell roots, dependency attestations, and
  -- the calibration needed by both physical and logical scene consumers.
  -- v4 keeps the v3 payload shape but serializes the physical-cell Y
  -- origin through the canonical matrix-altitude conversion, so a stale
  -- v3 cell with the old origin scale must rebuild.
  cacheFormat = "field-cell-cache-v3",
  indexSchema = "g4-field-cell-index-v3",
  cellSchema = "g4-field-cell-v4",
}

DerivedAssetContract.fieldActors = {
  cacheFormat = "field-actor-cache-v2",
  schema = "g4-field-actor-v3",
  indexSchema = "g4-field-actor-index-v3",
}

DerivedAssetContract.fieldCamera = {
  cacheFormat = "g4-field-camera-cache-v1",
  schema = "g4-field-camera-profiles-v1",
}

DerivedAssetContract.fieldMapData = {
  cacheFormat = "g4-field-map-cache-v1",
  -- The generated field record carries the day/night map-header music block
  -- as canonical audio sequence references (never bare source suffixes), so
  -- the runtime field-music policy reads it directly and never decorates
  -- symbols. v5 drops the source-only volumeIndex from the soundplates
  -- records: the BGM duck and ambient targets derived from the raw volume
  -- index are emitted instead (nothing above index two), the disable flag
  -- comes from the frozen reference rule scoped to the map, and raw
  -- soundplateSoundID never reaches the record. v4 added the flag/traversal
  -- music policy and the semantic soundplates array to the record.
  -- v7 makes initScripts a strict source-independent descriptor union. v8
  -- normalizes the retail unbound-script marker (0xFFFF) to zero so runtime
  -- binding and interaction audits never interpret raw ROM data. v9
  -- publishes semantic object movement types instead of raw HGSS selectors.
  -- v10 publishes the semantic field-use policy (Fly/Teleport/escape
  -- permissions, Flash/dark facts, cave environment, Union/Colosseum
  -- exclusion, and the Ice Path/Alph source exceptions) plus proven
  -- facing-actor obstacle kinds on object events.
  -- v11 carries the normalized renderer environment (parsed field-light
  -- records, the area edge-color table, the catalog weather id, and its
  -- fog preset) so logical maps stay drawable without a visual scene.
  fieldSchema = "g4-field-map-v11",
  -- The teleport landing index is a separate family-level record carrying
  -- cited spawn-keyed outdoor arrival destinations (never source numeric
  -- identities); the runtime return planner reads it, never producer data.
  spawnIndexSchema = "g4-field-spawn-index-v1",
}

DerivedAssetContract.messages = {
  cacheFormat = "field-message-cache-v3",
  schema = "g4-field-message-bank-v1",
  indexSchema = "g4-field-message-index-v1",
  provenanceSchema = "g4-field-message-provenance-v1",
}

-- v6/v5: focus indicators use four ordered white alpha masks per frame,
-- each carrying its palette slot and rect, instead of separate slot keys.
-- v5/v4: focus indicators use four white alpha masks per frame, keyed by
-- source palette slots, instead of a precolored single image.
-- v4: the font class requires font IDs 0 and 4 in one atomic publication;
-- v3: the font class gains a required semantic glyph mask atlas (categorical
-- foreground/shadow/background classes, distinct from the composited RGB
-- atlas) so palette-driven presentation can recolor glyphs against an
-- arbitrary runtime palette instead of the font's own baked color bands.
DerivedAssetContract.font = {
  cacheFormat = "field-font-cache-v6",
  schema = "g4-field-font-v5",
}

DerivedAssetContract.scripts = {
  -- v7 carries the deterministic per-member transitive script-audio closure
  -- (memberAudioSequences, keyed by decimal member id, possibly empty) and
  -- the v2 member attestation sidecar with per-resource direct audio and
  -- cross-script targets, so a sparse field can demand exactly the audio
  -- its scripts reach; older generated script data rebuilds.
  -- v6 keeps the v5 layout and requires every complete-index resource
  -- entry to carry its canonical decoded-resource hash (published per
  -- member beside the bodies, joined into the index by the summary), so a
  -- hashless older index rebuilds instead of reading as ready.
  -- v5 moves the generation summary (index, provenance, coverage, marker)
  -- under a `metadata/` child of the generation directory, disjoint from
  -- the `members/` payload roots, so one summary publication can own the
  -- metadata directory plus the active selector without replacing members.
  -- v4 shards the generated corpus into immutable generations and member
  -- roots. The active selector is separate from the generation contents.
  cacheFormat = "script-cache-v5",
  indexSchema = "g4-script-index-v4",
  provenanceSchema = "g4-script-provenance-v2",
}

DerivedAssetContract.fieldWeather = {
  cacheFormat = "field-weather-cache-v1",
  schema = "g4-field-weather-v1",
}

DerivedAssetContract.newGameInit = {
  cacheFormat = "g4-new-game-init-cache-v1",
  -- v3 carries the source-grounded initial player-room location alongside
  -- the ordered startup operations; stale v2 artifacts rebuild.
  schema = "g4-new-game-init-v3",
}

DerivedAssetContract.fieldEffects = {
  -- v9 adds the source-selected follower reaction clips to the field-effect
  -- index and publishes their shared-model dynamic descriptors.
  cacheFormat = "field-effect-cache-v9",
  indexSchema = "g4-field-effect-index-v3",
}

DerivedAssetContract.fieldEmotes = {
  cacheFormat = "field-emotes-cache-v2",
  schema = "g4-field-emote-v1",
}

DerivedAssetContract.fieldUi = {
  cacheFormat = "field-ui-cache-v1",
  schema = "g4-field-ui-v20",
}

DerivedAssetContract.intro = {
  cacheFormat = "intro-cache-v14",
  schema = "g4-intro-assets-v14",
  provenanceSchema = "g4-intro-provenance-v1",
}

DerivedAssetContract.starterChoice = {
  cacheFormat = "starter-choice-cache-v7",
  schema = "g4-starter-choice-v7",
}

-- The mon class carries the complete species/form/move/ability/growth
-- catalog plus the party-icon and portrait atlas pages with their selection
-- manifests. The semantic catalog stages apart from pixels; one layout
-- manifest per kind assigns every reachable selector to a bounded page, and
-- each page stages as its own image. Following-mon drawable definitions stay
-- in the field-actor class; the catalog references field-actor visual IDs
-- only. Item identity lives in the item class, never here: v3 drops the
-- former generated item collection so item-only metadata changes never
-- invalidate mon buckets.
DerivedAssetContract.mons = {
  cacheFormat = "mon-cache-v1",
  catalogSchema = "g4-mon-catalog-v4",
  -- v2 replaces the whole-atlas index with a page inventory: the index binds
  -- the catalog hash to one marker per icon/portrait page.
  indexSchema = "g4-mon-index-v2",
  -- v2 replaces the single global image with per-page records: each selector
  -- entry carries its zero-based page id and page-local rectangles.
  iconManifestSchema = "g4-mon-icon-manifest-v2",
  portraitManifestSchema = "g4-mon-portrait-manifest-v2",
}

-- The item class carries the source-independent item catalog (definitions,
-- pockets, pocket names) plus the item-icon atlas with its manifest. The
-- mon package and the Bag runtime resolve item identity through this class.
-- v2 adds held-item action metadata (isHm, canHold, heldFormEffect), so a
-- stale v1 cache without those facts must fail readiness. v3 adds semantic
-- party-use metadata (partyUse), and v4 adds source item prices, so older
-- catalogs must fail readiness.
DerivedAssetContract.items = {
  cacheFormat = "item-cache-v4",
  catalogSchema = "g4-item-catalog-v4",
  indexSchema = "g4-item-index-v1",
  iconManifestSchema = "g4-item-icons-v1",
}

DerivedAssetContract.followerInteractions = {
  cacheFormat = "follower-interaction-cache-v1",
  schema = "g4-follower-interactions-v3",
}

DerivedAssetContract.mart = {
  cacheFormat = "mart-cache-v1",
  catalogSchema = "g4-mart-catalog-v1",
  -- v2 removes unreachable page focus; page controls use feedback while
  -- independent focus remains on items and Cancel.
  schema = "g4-mart-presentation-v2",
}

-- The bag class carries the source-independent field-bag presentation: the
-- upper-pane hero (gender backdrops, description frame, hero models with
-- pocket-indexed animation states, camera/transform facts, pocket framing
-- records with the fixed transition duration, the eight-entry edge-color
-- table) plus the lower-
-- pane controls (one pocket strip per active pocket carrying the persistent
-- selected-pocket treatment, six item slots, count readout, Cancel with
-- its source-centered label area, the browse/action/quantity count-variant
-- backgrounds, the move count/origin-variant backgrounds, four action
-- slots, six quantity controls with static press visuals, the retained
-- selected-item panel, the short/tall lower-message geometry, activation
-- feedback timing with control visuals, the unchanged/changed move commit
-- clips, the original/candidate move target visuals, semantic action
-- text/templates, the toss prompt placement with its post-choice result
-- text, and the two registration-slot markers). Item icons stay in the item
-- class; the bag manifest references no icon pixels.
DerivedAssetContract.bag = {
  cacheFormat = "bag-cache-v2",
  schema = "g4-bag-assets-v17",
}

-- The party class carries the source-independent native party
-- presentation: the canonical panes, six slotted panels pairing chrome
-- variants with text/HP subrectangles, semantic message windows, exact icon
-- animation timelines, text palette roles with gender labels, window-relative
-- numeric placement, source-shaped context-menu layouts with generated frame
-- visuals, cursor/ball/held/status/feedback visuals with source timing,
-- dpad/touch navigation tables, lowered bank-300 text, source numeric glyphs,
-- and Shiny Leaf/crown badge frames. Species icons stay in the mon class;
-- the party manifest references no icon pixels.
DerivedAssetContract.party = {
  cacheFormat = "party-cache-v1",
  schema = "g4-party-presentation-v6",
}

-- The PC family retains its source-independent Storage, Mailbox, Mail and
-- Photo Album presentation records as one independently published family.
DerivedAssetContract.pc = {
  cacheFormat = "pc-cache-v1",
  schema = "g4-pc-v1",
}

DerivedAssetContract.audio = {
  cacheFormat = "g4-audio-cache-v1",
  -- The index carries the per-class symbol maps sequenceBySymbol and
  -- bankBySymbol (wave-archive symbols are not indexed), per-player entries
  -- with only runtime-relevant fields (the parser keeps source facts such as
  -- the heap budget), and no stored payload path on sequence/bank records:
  -- every path derives from the numeric id (AudioCache.sequencePath/bankPath),
  -- so a redundant `file` field is malformed index data.
  indexSchema = "g4-audio-index-v5",
  -- The sequence asset carries a closed semantic instruction vocabulary and
  -- the NNS initial-volume domain; v9 rejects values above 0x7F.
  sequenceSchema = "g4-audio-sequence-v9",
  -- v5 includes exact silent DUMMY leaves and the 0xFF release sentinel.
  bankSchema = "g4-audio-bank-v5",
  sampleSchema = "g4-audio-sample-v4",
  provenanceSchema = "g4-audio-provenance-v1",
}

-- The mesh batch format constants (magic, version, stride, header size,
-- index widths) have their own owner (G4MeshFormat); the vertex-layout
-- version aliases that owner's version, so nothing mesh-shaped lives here.

return DerivedAssetContract
