-- Independent battle-mechanics evidence. A fidelity record travels with
-- its provenance: whether its expectations were transcribed from the
-- native source, observed from a user-owned dump, or cross-checked against
-- a secondary implementation, plus the exact revision, location, evidence
-- identity, and oracle method behind every expected value. Validation
-- rejects provenance-incomplete records before anything runs, execution
-- returns the production actual, and comparison reports mismatches with
-- both sides attached. Expectations must never be generated by the
-- production function under test, and a skipped gate is missing evidence,
-- never a pass.

---@class FidelityFixtureProvenance
---@field basis string source-derived, observed-rom, or secondary-cross-check
---@field sourceRevision string revision or dump identity behind the expectations
---@field sourceLocation string file, symbol, or dump scope behind the expectations
---@field evidenceIdentity string? dump member or observation binding the evidence
---@field oracleMethod string how the expectations were derived without production code

---@class FidelityFixtureRecord
---@field provenance FidelityFixtureProvenance evidence behind the expectations
---@field input table<string, unknown> setup the oracle executes
---@field expected table<string, unknown> independently derived expectations

---@class FidelityFixtureMismatch
---@field kind string divergence boundary
---@field expected table<string, unknown> independently derived expectations
---@field actual table<string, unknown> production actual at the divergence

---@class BattleFidelityFixture
local BattleFidelityFixture = {}

local BASES = {
  ["source-derived"] = true,
  ["observed-rom"] = true,
  ["secondary-cross-check"] = true,
}

---@param record unknown fixture record under validation
---@return boolean true when the record carries complete provenance with its input and expectations
local function checkProvenance(record)
  if type(record) ~= "table" then
    error("fixture records must be tables", 2)
  end
  local candidate = record --[[@as table<string, unknown>]]
  if type(candidate.provenance) ~= "table" then
    error("fixture records carry their provenance record", 2)
  end
  local provenance = candidate.provenance --[[@as table<string, unknown>]]
  if
    BASES[
      provenance.basis --[[@as string]]
    ] ~= true
  then
    error("fixture provenance names a known evidence basis", 2)
  end
  for _, field in ipairs({ "sourceRevision", "sourceLocation", "oracleMethod" }) do
    if type(provenance[field]) ~= "string" or provenance[field] == "" then
      error("fixture provenance names its " .. field, 2)
    end
  end
  if
    provenance.basis == "observed-rom"
    and (type(provenance.evidenceIdentity) ~= "string" or provenance.evidenceIdentity == "")
  then
    error("dump-observed fixtures name their evidence identity", 2)
  end
  if candidate.input == nil then
    error("fixture records carry their input", 2)
  end
  if candidate.expected == nil then
    error("fixture records carry their expected result", 2)
  end
  return true
end

--- Validates one fixture record: complete provenance plus a present input
--- and expected result. Throws on provenance-incomplete records.
---@param record FidelityFixtureRecord fixture record under validation
---@return boolean true when the record is complete
function BattleFidelityFixture.validate(record)
  return checkProvenance(record)
end

--- Executes the oracle body against a validated record and returns its
--- actual result for comparison.
---@param fn fun(): table<string, unknown> oracle body producing the actual result
---@param record FidelityFixtureRecord fixture record the oracle runs under
---@return table<string, unknown> the production actual
function BattleFidelityFixture.run(fn, record)
  checkProvenance(record)
  if type(fn) ~= "function" then
    error("fixture oracles execute a function body", 2)
  end
  return fn()
end

---@param want unknown expected side under comparison
---@param got unknown actual side under comparison
---@param active table<string, boolean> traversal keys on the current path
---@return boolean true when both sides match structurally
local function sidesEqual(want, got, active)
  if type(want) ~= type(got) then
    return false
  end
  if type(want) ~= "table" then
    return want == got
  end
  local key = tostring(want) .. "/" .. tostring(got)
  if active[key] == true then
    return true
  end
  active[key] = true
  local expected = want --[[@as table<unknown, unknown>]]
  local actual = got --[[@as table<unknown, unknown>]]
  for field, value in pairs(expected) do
    if not sidesEqual(value, actual[field], active) then
      return false
    end
  end
  for field in pairs(actual) do
    if expected[field] == nil then
      return false
    end
  end
  active[key] = nil
  return true
end

--- Compares a production actual against independently derived
--- expectations. Returns nil on exact match, or a mismatch carrying both
--- sides when any value diverges.
---@param actual table<string, unknown> production actual under comparison
---@param wrapper { expected: table<string, unknown> } independently derived expectations
---@return FidelityFixtureMismatch? the divergence, or nil on exact match
function BattleFidelityFixture.compare(actual, wrapper)
  if type(wrapper) ~= "table" or wrapper.expected == nil then
    error("fixture comparisons carry their expected result", 2)
  end
  if sidesEqual(actual, wrapper.expected, {}) then
    return nil
  end
  return { kind = "state", expected = wrapper.expected, actual = actual }
end

return BattleFidelityFixture
