-- Stable error codes for the field-script platform. Every subsystem
-- (validator, compiler, registry, loader, scheduler, tasks, save)
-- raises Errors with exactly these codes; modules must reference the named
-- constants, never bare literals, so a rename stays in one place.

local Errors = {}

Errors.SCRIPT_SCHEMA_INVALID = "SCRIPT_SCHEMA_INVALID"
Errors.SCRIPT_API_UNSUPPORTED = "SCRIPT_API_UNSUPPORTED"
Errors.SCRIPT_DUPLICATE_ID = "SCRIPT_DUPLICATE_ID"
Errors.SCRIPT_UNKNOWN_OPERATION = "SCRIPT_UNKNOWN_OPERATION"
Errors.SCRIPT_INVALID_REFERENCE = "SCRIPT_INVALID_REFERENCE"
Errors.SCRIPT_CALL_TARGET_MISSING = "SCRIPT_CALL_TARGET_MISSING"
Errors.SCRIPT_LABEL_MISSING = "SCRIPT_LABEL_MISSING"
Errors.SCRIPT_UNSUPPORTED_REACHABLE = "SCRIPT_UNSUPPORTED_REACHABLE"
Errors.SCRIPT_STEP_BUDGET_EXCEEDED = "SCRIPT_STEP_BUDGET_EXCEEDED"
Errors.SCRIPT_CONTEXT_SLOTS_EXHAUSTED = "SCRIPT_CONTEXT_SLOTS_EXHAUSTED"
Errors.SCRIPT_CALLER_SIGNAL_INVALID = "SCRIPT_CALLER_SIGNAL_INVALID"
Errors.SCRIPT_LOCK_NOT_OWNED = "SCRIPT_LOCK_NOT_OWNED"
Errors.SCRIPT_ACTOR_NOT_FOUND = "SCRIPT_ACTOR_NOT_FOUND"
Errors.SCRIPT_ACTOR_BUSY = "SCRIPT_ACTOR_BUSY"
Errors.SCRIPT_BACKGROUND_FORBIDDEN = "SCRIPT_BACKGROUND_FORBIDDEN"
Errors.SCRIPT_SERVICE_MISSING = "SCRIPT_SERVICE_MISSING"
Errors.SCRIPT_TASK_VERSION_UNSUPPORTED = "SCRIPT_TASK_VERSION_UNSUPPORTED"
Errors.SCRIPT_TASK_UNSERIALIZABLE = "SCRIPT_TASK_UNSERIALIZABLE"
Errors.SCRIPT_TASK_CALLBACK_FAULT = "SCRIPT_TASK_CALLBACK_FAULT"
Errors.SCRIPT_WARP_FAILED = "SCRIPT_WARP_FAILED"
Errors.SCRIPT_SAVE_REVISION_MISMATCH = "SCRIPT_SAVE_REVISION_MISMATCH"
Errors.SCRIPT_REGISTRY_FINGERPRINT_MISMATCH = "SCRIPT_REGISTRY_FINGERPRINT_MISMATCH"
Errors.SCRIPT_WRAPPER_INVALID = "SCRIPT_WRAPPER_INVALID"
Errors.SCRIPT_LOAD_FAILED = "SCRIPT_LOAD_FAILED"
Errors.SCRIPT_REGISTRY_SEALED = "SCRIPT_REGISTRY_SEALED"
Errors.SCRIPT_MENU_ALREADY_BUILDING = "SCRIPT_MENU_ALREADY_BUILDING"
Errors.SCRIPT_MENU_NOT_INITIALIZED = "SCRIPT_MENU_NOT_INITIALIZED"
Errors.SCRIPT_MENU_EMPTY = "SCRIPT_MENU_EMPTY"
Errors.SCRIPT_MENU_MESSAGE_UNRESOLVED = "SCRIPT_MENU_MESSAGE_UNRESOLVED"
Errors.SCRIPT_STYLE_UNKNOWN = "SCRIPT_STYLE_UNKNOWN"
Errors.FEATURE_UNAVAILABLE = "FEATURE_UNAVAILABLE"

return Errors
