-- Stable error codes for the engine field layer: event state, actors,
-- terrain surfaces, render-queue classification, warp resolution, map
-- loading/saving, field coordinates, transitions, dialogue state,
-- animated models/materials, scene/mesh/GPU asset loading.
-- Every module in this layer raises Errors with exactly these codes; modules
-- must reference the named constants, never bare literals, so a rename stays
-- in one place. The script subsystem keeps its own catalogue
-- (script/errors.lua); the audio subsystem keeps its own
-- (audio/AudioErrors.lua). Pure domain module: no love dependency.

local FieldErrors = {}

FieldErrors.EVENT_STATE_TOO_LARGE = "EVENT_STATE_TOO_LARGE"
FieldErrors.EVENT_FLAG_VALUE_INVALID = "EVENT_FLAG_VALUE_INVALID"
FieldErrors.EVENT_VAR_VALUE_INVALID = "EVENT_VAR_VALUE_INVALID"
FieldErrors.EVENT_FLAG_ID_INVALID = "EVENT_FLAG_ID_INVALID"
FieldErrors.EVENT_VAR_ID_INVALID = "EVENT_VAR_ID_INVALID"
FieldErrors.AUXILIARY_UI_INVALID = "AUXILIARY_UI_INVALID"
FieldErrors.FIELD_OVERWORLD_LIFECYCLE_INVALID = "FIELD_OVERWORLD_LIFECYCLE_INVALID"

FieldErrors.RENDER_QUEUE_UNKNOWN_ALPHA_CLASS = "RENDER_QUEUE_UNKNOWN_ALPHA_CLASS"

FieldErrors.ACTOR_OCCUPANCY_CONFLICT = "ACTOR_OCCUPANCY_CONFLICT"
FieldErrors.ACTOR_FACING_INVALID = "ACTOR_FACING_INVALID"
FieldErrors.ACTOR_VISUAL_MISSING = "ACTOR_VISUAL_MISSING"
FieldErrors.ACTOR_DUPLICATE_ID = "ACTOR_DUPLICATE_ID"
FieldErrors.ACTOR_POSE_DIRECTION_MISSING = "ACTOR_POSE_DIRECTION_MISSING"
FieldErrors.ACTOR_POSE_MISSING = "ACTOR_POSE_MISSING"
FieldErrors.ACTOR_SURFACE_MISSING = "ACTOR_SURFACE_MISSING"
FieldErrors.ACTOR_SURFACE_AMBIGUOUS = "ACTOR_SURFACE_AMBIGUOUS"
FieldErrors.ACTOR_OVERRIDE_OWNER_MISMATCH = "ACTOR_OVERRIDE_OWNER_MISMATCH"
FieldErrors.ACTOR_DRAW_FRAME_MISSING = "ACTOR_DRAW_FRAME_MISSING"
FieldErrors.ACTOR_DRAW_VISUAL_MISSING = "ACTOR_DRAW_VISUAL_MISSING"
FieldErrors.ACTOR_PARTNER_ID_INVALID = "ACTOR_PARTNER_ID_INVALID"
FieldErrors.ACTOR_PARTNER_MAP_MISMATCH = "ACTOR_PARTNER_MAP_MISMATCH"
FieldErrors.ACTOR_PARTNER_SOLID_INVALID = "ACTOR_PARTNER_SOLID_INVALID"
FieldErrors.ACTOR_PARTNER_FACING_INVALID = "ACTOR_PARTNER_FACING_INVALID"
FieldErrors.ACTOR_PARTNER_VISUAL_MISSING = "ACTOR_PARTNER_VISUAL_MISSING"
FieldErrors.ACTOR_PARTNER_ALREADY_INSTALLED = "ACTOR_PARTNER_ALREADY_INSTALLED"
FieldErrors.ACTOR_PARTNER_NOT_INSTALLED = "ACTOR_PARTNER_NOT_INSTALLED"
FieldErrors.FOLLOWER_APPEARANCE_GEOMETRY_INVALID = "FOLLOWER_APPEARANCE_GEOMETRY_INVALID"

FieldErrors.FIELD_ACTOR_INDEX_UNAVAILABLE = "FIELD_ACTOR_INDEX_UNAVAILABLE"
FieldErrors.FIELD_ACTOR_VISUAL_UNAVAILABLE = "FIELD_ACTOR_VISUAL_UNAVAILABLE"
FieldErrors.FIELD_ACTOR_ATLAS_MISSING = "FIELD_ACTOR_ATLAS_MISSING"
FieldErrors.FIELD_ACTOR_SPRITE_NOT_COMPILED = "FIELD_ACTOR_SPRITE_NOT_COMPILED"
FieldErrors.FIELD_ACTOR_RELEASE_UNKNOWN = "FIELD_ACTOR_RELEASE_UNKNOWN"
FieldErrors.FIELD_ACTOR_RELEASE_UNBALANCED = "FIELD_ACTOR_RELEASE_UNBALANCED"
FieldErrors.FIELD_ACTOR_GEOMETRY_MISSING = "FIELD_ACTOR_GEOMETRY_MISSING"

FieldErrors.TERRAIN_SURFACE_NOT_FOUND = "TERRAIN_SURFACE_NOT_FOUND"
FieldErrors.TERRAIN_SURFACE_AMBIGUOUS = "TERRAIN_SURFACE_AMBIGUOUS"
FieldErrors.TERRAIN_SURFACE_DISCONNECTED = "TERRAIN_SURFACE_DISCONNECTED"

FieldErrors.FIELD_COORDINATES_INVALID = "FIELD_COORDINATES_INVALID"
FieldErrors.FIELD_COORDINATES_OUT_OF_COVERAGE = "FIELD_COORDINATES_OUT_OF_COVERAGE"

FieldErrors.MAP_TRANSITION_UNRESOLVED_SOURCE_DOOR = "MAP_TRANSITION_UNRESOLVED_SOURCE_DOOR"
FieldErrors.MAP_TRANSITION_INGRESS_FAILED = "MAP_TRANSITION_INGRESS_FAILED"
FieldErrors.MAP_TRANSITION_EGRESS_FAILED = "MAP_TRANSITION_EGRESS_FAILED"
FieldErrors.MAP_TRANSITION_PROFILE_UNSUPPORTED = "MAP_TRANSITION_PROFILE_UNSUPPORTED"

FieldErrors.MAP_PROP_ANIM_UNKNOWN = "MAP_PROP_ANIM_UNKNOWN"
FieldErrors.MAP_PROP_AMBIGUOUS_DOOR = "MAP_PROP_AMBIGUOUS_DOOR"
FieldErrors.MAP_PROP_UNCOVERED_DOOR = "MAP_PROP_UNCOVERED_DOOR"

FieldErrors.MAP_SCENE_UNSUPPORTED_TRANSFORM_MODE = "MAP_SCENE_UNSUPPORTED_TRANSFORM_MODE"
FieldErrors.MAP_SCENE_UNKNOWN_MODEL_KIND = "MAP_SCENE_UNKNOWN_MODEL_KIND"
FieldErrors.MAP_SCENE_UNSUPPORTED_SCHEMA = "MAP_SCENE_UNSUPPORTED_SCHEMA"

FieldErrors.GPU_ASSET_UNKNOWN_WRAP = "GPU_ASSET_UNKNOWN_WRAP"

FieldErrors.ANIM_MATERIAL_VARIANT_MISSING = "ANIM_MATERIAL_VARIANT_MISSING"
FieldErrors.ANIM_STATE_BAD_CATEGORY = "ANIM_STATE_BAD_CATEGORY"
FieldErrors.ANIM_STATE_ZERO_BINDING = "ANIM_STATE_ZERO_BINDING"
FieldErrors.ANIM_STATE_SAME_KIND_IN_USE = "ANIM_STATE_SAME_KIND_IN_USE"
FieldErrors.ANIM_INSTANCE_UNKNOWN_ANIMATION = "ANIM_INSTANCE_UNKNOWN_ANIMATION"

FieldErrors.MODEL_DEF_NO_KEY = "MODEL_DEF_NO_KEY"
FieldErrors.MODEL_DEF_BAD_SOURCE_BACKEND = "MODEL_DEF_BAD_SOURCE_BACKEND"
FieldErrors.MODEL_DEF_NO_NODES = "MODEL_DEF_NO_NODES"
FieldErrors.MODEL_DEF_NO_MESHES = "MODEL_DEF_NO_MESHES"
FieldErrors.MODEL_DEF_NO_MATERIALS = "MODEL_DEF_NO_MATERIALS"
FieldErrors.MODEL_DEF_BAD_ANIMATIONS = "MODEL_DEF_BAD_ANIMATIONS"
FieldErrors.MODEL_DEF_BAD_BACKEND = "MODEL_DEF_BAD_BACKEND"
FieldErrors.MODEL_DEF_DUPLICATE_ANIMATION = "MODEL_DEF_DUPLICATE_ANIMATION"
FieldErrors.MODEL_DEF_DUPLICATE_SEMANTIC = "MODEL_DEF_DUPLICATE_SEMANTIC"
FieldErrors.MODEL_DEF_NAME_SEMANTIC_COLLISION = "MODEL_DEF_NAME_SEMANTIC_COLLISION"
FieldErrors.NITRO_DESC_NO_KEY = "NITRO_DESC_NO_KEY"

FieldErrors.POSE_NITRO_JOINT_CLIP_NOT_COMPILED = "POSE_NITRO_JOINT_CLIP_NOT_COMPILED"
FieldErrors.POSE_NITRO_NO_TRANSFORM_PROGRAM = "POSE_NITRO_NO_TRANSFORM_PROGRAM"
FieldErrors.POSE_NITRO_DRAW_MISSING = "POSE_NITRO_DRAW_MISSING"

FieldErrors.MESH_TOO_SMALL = "MESH_TOO_SMALL"
FieldErrors.MESH_BAD_MAGIC = "MESH_BAD_MAGIC"
FieldErrors.MESH_BAD_VERSION = "MESH_BAD_VERSION"
FieldErrors.MESH_BAD_STRIDE = "MESH_BAD_STRIDE"
FieldErrors.MESH_BAD_INDEX_WIDTH = "MESH_BAD_INDEX_WIDTH"
FieldErrors.MESH_BAD_INDEX_COUNT = "MESH_BAD_INDEX_COUNT"
FieldErrors.MESH_BAD_LENGTH = "MESH_BAD_LENGTH"
FieldErrors.MESH_NONFINITE = "MESH_NONFINITE"
FieldErrors.MESH_BAD_COLOR_SOURCE = "MESH_BAD_COLOR_SOURCE"
FieldErrors.MESH_INDEX_OUT_OF_RANGE = "MESH_INDEX_OUT_OF_RANGE"

FieldErrors.FONT_ATLAS_MISSING = "FONT_ATLAS_MISSING"
FieldErrors.FONT_GLYPH_MISSING = "FONT_GLYPH_MISSING"
FieldErrors.FONT_DEF_MISSING = "FONT_DEF_MISSING"
FieldErrors.FONT_DEF_INVALID = "FONT_DEF_INVALID"
FieldErrors.FONT_MASK_ATLAS_MISSING = "FONT_MASK_ATLAS_MISSING"
FieldErrors.FONT_FOCUS_IMAGE_MISSING = "FONT_FOCUS_IMAGE_MISSING"
FieldErrors.FONT_COLOR_INDEX_INVALID = "FONT_COLOR_INDEX_INVALID"
FieldErrors.FONT_FOCUS_FIELD_INVALID = "FONT_FOCUS_FIELD_INVALID"
FieldErrors.DIALOGUE_ALREADY_OPEN = "DIALOGUE_ALREADY_OPEN"

FieldErrors.PLAYER_AVATAR_INVALID = "PLAYER_AVATAR_INVALID"

FieldErrors.MON_ICON_MANIFEST_UNAVAILABLE = "MON_ICON_MANIFEST_UNAVAILABLE"
FieldErrors.MON_ICON_ATLAS_MISSING = "MON_ICON_ATLAS_MISSING"
FieldErrors.MON_ICON_UNKNOWN_KEY = "MON_ICON_UNKNOWN_KEY"

FieldErrors.ITEM_ICON_MANIFEST_UNAVAILABLE = "ITEM_ICON_MANIFEST_UNAVAILABLE"
FieldErrors.ITEM_ICON_ATLAS_MISSING = "ITEM_ICON_ATLAS_MISSING"
FieldErrors.ITEM_ICON_UNKNOWN_KEY = "ITEM_ICON_UNKNOWN_KEY"

FieldErrors.PLAYER_DATA_INVALID = "PLAYER_DATA_INVALID"
FieldErrors.PLAYER_DATA_NAME_INVALID = "PLAYER_DATA_NAME_INVALID"
FieldErrors.PLAYER_DATA_GENDER_INVALID = "PLAYER_DATA_GENDER_INVALID"
FieldErrors.PLAYER_DATA_TRAINER_ID_INVALID = "PLAYER_DATA_TRAINER_ID_INVALID"
FieldErrors.PLAYER_DATA_MONEY_INVALID = "PLAYER_DATA_MONEY_INVALID"
FieldErrors.PLAYER_DATA_TEXT_FRAME_INVALID = "PLAYER_DATA_TEXT_FRAME_INVALID"
FieldErrors.PLAYER_DATA_TEXT_SPEED_INVALID = "PLAYER_DATA_TEXT_SPEED_INVALID"

FieldErrors.FIELD_UI_FRAME_ATLAS_MISSING = "FIELD_UI_FRAME_ATLAS_MISSING"
FieldErrors.FIELD_UI_CONTINUE_CURSOR_MISSING = "FIELD_UI_CONTINUE_CURSOR_MISSING"
FieldErrors.FIELD_UI_SIGNPOST_TILES_MISSING = "FIELD_UI_SIGNPOST_TILES_MISSING"
FieldErrors.FIELD_UI_WAYFINDING_MISSING = "FIELD_UI_WAYFINDING_MISSING"
FieldErrors.FIELD_UI_START_MENU_ICONS_MISSING = "FIELD_UI_START_MENU_ICONS_MISSING"
FieldErrors.FIELD_UI_START_MENU_CHROME_MISSING = "FIELD_UI_START_MENU_CHROME_MISSING"
FieldErrors.FIELD_UI_START_MENU_POKE_ICONS_MISSING = "FIELD_UI_START_MENU_POKE_ICONS_MISSING"
FieldErrors.FIELD_UI_TRAINER_CARD_FRONT_MISSING = "FIELD_UI_TRAINER_CARD_FRONT_MISSING"
FieldErrors.FIELD_UI_YES_NO_PROMPT_MISSING = "FIELD_UI_YES_NO_PROMPT_MISSING"

FieldErrors.APPLICATION_REGISTRY_INVALID_DESCRIPTOR = "APPLICATION_REGISTRY_INVALID_DESCRIPTOR"
FieldErrors.APPLICATION_REGISTRY_DUPLICATE_ID = "APPLICATION_REGISTRY_DUPLICATE_ID"
FieldErrors.APPLICATION_REGISTRY_UNKNOWN_ID = "APPLICATION_REGISTRY_UNKNOWN_ID"
FieldErrors.APPLICATION_REGISTRY_INVALID_CONTROLLER = "APPLICATION_REGISTRY_INVALID_CONTROLLER"

FieldErrors.FIELD_PRESENTATION_UNKNOWN_APPLICATION = "FIELD_PRESENTATION_UNKNOWN_APPLICATION"

FieldErrors.FIELD_MAP_UNKNOWN = "FIELD_MAP_UNKNOWN"
FieldErrors.FIELD_DESTINATION_MAP_UNKNOWN = "FIELD_DESTINATION_MAP_UNKNOWN"
FieldErrors.FIELD_DESTINATION_WARP_UNKNOWN = "FIELD_DESTINATION_WARP_UNKNOWN"
FieldErrors.FIELD_DYNAMIC_WARP_UNSUPPORTED = "FIELD_DYNAMIC_WARP_UNSUPPORTED"
FieldErrors.FIELD_MAP_VISUAL_CACHE_MISSING = "FIELD_MAP_VISUAL_CACHE_MISSING"
FieldErrors.FIELD_MAP_DATA_CACHE_MISSING = "FIELD_MAP_DATA_CACHE_MISSING"
FieldErrors.FIELD_MAP_TERRAIN_CACHE_MISSING = "FIELD_MAP_TERRAIN_CACHE_MISSING"
FieldErrors.FIELD_MAP_VISUAL_CACHE_INVALID = "FIELD_MAP_VISUAL_CACHE_INVALID"
FieldErrors.FIELD_MAP_DATA_CACHE_INVALID = "FIELD_MAP_DATA_CACHE_INVALID"
FieldErrors.FIELD_MAP_TERRAIN_CACHE_INVALID = "FIELD_MAP_TERRAIN_CACHE_INVALID"
FieldErrors.FIELD_MAP_NEIGHBOR_CACHE_MISSING = "FIELD_MAP_NEIGHBOR_CACHE_MISSING"
FieldErrors.FIELD_MAP_COLLISION_CACHE_MISSING = "FIELD_MAP_COLLISION_CACHE_MISSING"
FieldErrors.FIELD_MAP_CAMERA_MISMATCH = "FIELD_MAP_CAMERA_MISMATCH"
FieldErrors.FIELD_MAP_WORLD_INVALID = "FIELD_MAP_WORLD_INVALID"
FieldErrors.MAP_INIT_UNSUPPORTED_LIFECYCLE = "MAP_INIT_UNSUPPORTED_LIFECYCLE"
FieldErrors.FIELD_CELL_CACHE_MISSING = "FIELD_CELL_CACHE_MISSING"
FieldErrors.FIELD_CELL_CACHE_INVALID = "FIELD_CELL_CACHE_INVALID"
FieldErrors.FIELD_COVERAGE_TERRAIN_CACHE_INVALID = "FIELD_COVERAGE_TERRAIN_CACHE_INVALID"

FieldErrors.FIELD_SAVE_VERSION_INVALID = "FIELD_SAVE_VERSION_INVALID"
FieldErrors.FIELD_SAVE_MAP_INVALID = "FIELD_SAVE_MAP_INVALID"
FieldErrors.FIELD_SAVE_COORDINATES_INVALID = "FIELD_SAVE_COORDINATES_INVALID"
FieldErrors.FIELD_SAVE_HEIGHT_INVALID = "FIELD_SAVE_HEIGHT_INVALID"
FieldErrors.FIELD_SAVE_SURFACE_INVALID = "FIELD_SAVE_SURFACE_INVALID"
FieldErrors.FIELD_SAVE_TERRAIN_DEPENDENCY_INVALID = "FIELD_SAVE_TERRAIN_DEPENDENCY_INVALID"
FieldErrors.FIELD_SAVE_FACING_INVALID = "FIELD_SAVE_FACING_INVALID"
FieldErrors.FIELD_SAVE_AVATAR_INVALID = "FIELD_SAVE_AVATAR_INVALID"
FieldErrors.FIELD_SAVE_WORLD_INVALID = "FIELD_SAVE_WORLD_INVALID"
FieldErrors.FIELD_SAVE_SCRIPTS_INVALID = "FIELD_SAVE_SCRIPTS_INVALID"
FieldErrors.FIELD_SAVE_AUXILIARY_UI_INVALID = "FIELD_SAVE_AUXILIARY_UI_INVALID"
FieldErrors.FIELD_SAVE_INVALID = "FIELD_SAVE_INVALID"
FieldErrors.FIELD_SAVE_SCHEMA_UNSUPPORTED = "FIELD_SAVE_SCHEMA_UNSUPPORTED"
FieldErrors.FIELD_SAVE_SURFACE_NOT_FOUND = "FIELD_SAVE_SURFACE_NOT_FOUND"
FieldErrors.FIELD_SAVE_SURFACE_AMBIGUOUS = "FIELD_SAVE_SURFACE_AMBIGUOUS"
FieldErrors.FIELD_SAVE_VERSION_MISMATCH = "FIELD_SAVE_VERSION_MISMATCH"
FieldErrors.FIELD_SAVE_PLAYER_DATA_INVALID = "FIELD_SAVE_PLAYER_DATA_INVALID"

return FieldErrors
